// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC02TK_hWAjMROKH0bizJ-l9-BEmqFym40',
    appId: '1:567411559292:web:006302007ecccb2b4832f9',
    messagingSenderId: '567411559292',
    projectId: 'jrd-sports-connect',
    authDomain: 'jrd-sports-connect.firebaseapp.com',
    storageBucket: 'jrd-sports-connect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUjIXI0KkYrOfsgY4UDgZH6L_gzDpdtqA',
    appId: '1:567411559292:android:0bcca7ec4df147ae4832f9',
    messagingSenderId: '567411559292',
    projectId: 'jrd-sports-connect',
    storageBucket: 'jrd-sports-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2oLrtGpJkyHDcDCaVc9OR1tsun3PgHR4',
    appId: '1:567411559292:ios:21140e392dba711a4832f9',
    messagingSenderId: '567411559292',
    projectId: 'jrd-sports-connect',
    storageBucket: 'jrd-sports-connect.appspot.com',
    iosBundleId: 'com.example.jrdSc',
  );
}

class E {
  static const String p1 = "abs*";
}
